MRFHOME=../..
GCC=gcc
LD=ld
ARCH=lnx
#ARCH=cc430  this won't work because wrong gcc and ld above - see dir usbrf etc for working makefile
DEVTYPE=hostsim
MRFID=0x00
MRFNET=0x25

include ${MRFHOME}/Makefile.inc
