
#define I2CSDAOUT P2OUT
#define I2CSDAIN P2IN
#define I2CSDADIR P2DIR
#define I2CSDABIT  BIT4
#define I2CSDAREN P2REN
#define I2CSDASEL P2SEL

#define I2CSCKOUT P2OUT
#define I2CSCKDIR P2DIR
#define I2CSCKBIT  BIT5
#define I2CSCKREN P2REN
#define I2CSCKSEL P2SEL


