language: c

addons:
  apt:
    packages:
      - gcc-msp430
      - msp430-libc
      - python-virtualenv

script:
  - make venv
  - export MRFBUS_HOME=$(pwd)
  - make testsetup
  - mkdir -p /tmp/mrftst/rftst  && cp ${MRFBUS_HOME}/rf_mrf.prj /tmp/mrftst/rftst/mrf.prj
  - cd /tmp/mrftst/rftst ; ${MRFBUS_HOME}/mrf_proj build
  - mkdir -p /tmp/mrftst/testrun  && cp ${MRFBUS_HOME}/test_mrf.prj /tmp/mrftst/testrun/mrf.prj
  - cd /tmp/mrftst/testrun ; ${MRFBUS_HOME}/mrf_proj build && ${MRFBUS_HOME}/mrf_proj runtests
