language: c

addons:
  apt:
    packages:
      - gcc-msp430
      - msp430-libc
      - python-virtualenv

script:
  - make venv
  - make tests
  - ./mrflib/tests/iqueue/test_01
  - export MRFBUS_HOME=$(pwd) ; ./run_tests
