language: c

addons:
  apt:
    packages:
      - gcc-msp430
      - msp430-libc

install:
   - cd land ; virtualenv venv  ;  source venv/bin/activate ; pip install -r requirements.txt

script:
  - make tests
  - ./mrflib/tests/iqueue/test_01
  - ./run_tests