language: c

addons:
  apt:
    packages:
      - gcc-msp430
      - msp430-libc
      - python-virtualenv

script:
  - make venv
  - export MRFBUS_HOME=$(pwd) && make tests
  - ./mrflib/tests/iqueue/test_01
  - mkdir testrun  && cp test_mrf.prj testrun/mrf.prj && cp land/install.py testrun
  - export MRFBUS_HOME=$(pwd) ; cd testrun ; ../mrf_proj build && ../mrf_proj runtests
