language: c

addons:
  apt:
    packages:
      - gcc-msp430
      - msp430-libc

install: "pip install -r land/requirements.txt"

script:
  - make tests
  - ./mrflib/tests/iqueue/test_01
  - ./run_tests