#!/bin/bash

#start mrfbus instances
TMP=/tmp/mrf_bus
LOGDIR=${TMP}/log
#
[ ! -d ${LOGDIR} ]  && mkdir -p ${LOGDIR} 

#stdbuf -oL examples/hostsim/bin/hostsim_0x01 > ${LOGDIR}/hostsim_0x01.log &

echo "" > ${LOGDIR}/mrfland.log 
stdbuf -o0 -i0 examples/host/bin/host_0x01 >> ${LOGDIR}/mrfland.log #host_0x01.log &
h01_pid=$!
echo $h01_pid

#stdbuf -o0 -i0  examples/stub/bin/hostsim_0x00 > ${LOGDIR}/stub.log&
#stub_pid=$!
#echo $stub_pid


function ctrl_c() {
        echo "** Trapped CTRL-C killing mfrbus instances"
        kill $h01_pid $stub_pid
        sleep 1
        echo "adios"
        exit 0

}


trap ctrl_c INT

# make sure everyone is up

sleep 1

echo "mrfbus instances running ... ctrl C to quit"
while [ 1 ] ; do
  sleep 1

done

echo "quitting"

sleep 2

kill $h01_pid

sleep 1

echo "run_tests adios at $(date)"







