#!/bin/bash

#start mrfbus instances
TMP=/tmp/mrf_bus
LOGDIR=log
#export MRFBUS_HOME=$(pwd)


#
[ ! -d $LOGDIR ] && echo "creating $LOGDIR" && mkdir -p $LOGDIR

# MRFBUS_HOME must be defined
[ -z "$MRFBUS_HOME" ] && echo "MRFBUS_HOME not defined" && exit -1

stdbuf -oL ${MRFBUS_HOME}/examples/hostsim/build/0x01/bin/hostsim_0x01 > ${LOGDIR}/hostsim_0x01.log &
h01_pid=$!
echo $h01_pid

stdbuf -oL ${MRFBUS_HOME}/examples/hostsim/build/0x02/bin/hostsim_0x02 > ${LOGDIR}/hostsim_0x02.log&
h02_pid=$!
echo $h02_pid

stdbuf -oL ${MRFBUS_HOME}/examples/hostsim/build/0x20/bin/hostsim_0x20 > ${LOGDIR}/hostsim_0x20.log&
h20_pid=$!
echo $h20_pid


stdbuf -oL ${MRFBUS_HOME}/examples/hostsim/build/0x2f/bin/hostsim_0x2f > ${LOGDIR}/hostsim_0x2f.log&
h2f_pid=$!
echo $h2f_pid


# make sure everyone is up

echo "all mrf instances started"

sleep 3

# need to start mrfland... ho ho ho



# need install.py locally
cp ${MRFBUS_HOME}/land/install_example.py  ./install.py
export PYTHONPATH=$(pwd):${MRFBUS_HOME}/land

source ${MRFBUS_HOME}/land/venv/bin/activate
stdbuf -oL  python ${MRFBUS_HOME}/land/test_server.py  > ${LOGDIR}/mrfland.log&
land_pid=$!
echo "land started "$land_pid

sleep 5

echo "starting core_tests.."
# run stubtst

python ${MRFBUS_HOME}/land/core_tests.py
rv=$?


#sleep 1
echo "killing processes  $h01_pid $h02_pid $h20_pid $h2f_pid $land_pid"
kill -SIGUSR1  $h01_pid $h02_pid $h20_pid $h2f_pid
kill $land_pid


#sleep 1
#deactivate


echo "run_tests adios at $(date)  rv ="$rv


if [ $rv == 0 ] ; then

    echo "PASSED"
else
    echo "FAILED"
fi

exit $rv
#exit $rv




