#!/bin/bash

#start mrfbus instances
TMP=/tmp/mrf_bus
LOGDIR=${TMP}/log
#

stdbuf -oL examples/hostsim/bin/hostsim_0x01 > ${LOGDIR}/hostsim_0x01.log &
h01_pid=$!
echo $h01_pid

stdbuf -oL examples/hostsim/bin/hostsim_0x02 > ${LOGDIR}/hostsim_0x02.log&
h02_pid=$!
echo $h02_pid

stdbuf -oL examples/hostsim/bin/hostsim_0x20 > ${LOGDIR}/hostsim_0x20.log&
h20_pid=$!
echo $h20_pid


stdbuf -oL examples/hostsim/bin/hostsim_0x2f > ${LOGDIR}/hostsim_0x2f.log&
h2f_pid=$!
echo $h2f_pid

stdbuf -oL  examples/stub/bin/hostsim_0x00 > ${LOGDIR}/stub.log&
stub_pid=$!
echo $stub_pid

# make sure everyone is up

echo "all mrf instances started"

#sleep 4

# need to start mrfland... ho ho ho




source land/venv/bin/activate
stdbuf -oL  python land/server.py  > ${LOGDIR}/mrfland.log&
land_pid=$!
echo "land started "$land_pid

sleep 2

# run stubtst

python land/core_tests.py


#sleep 1

kill $h01_pid $h02_pid $h20_pid $h2f_pid $stub_pid $land_pid
rv=$?

#sleep 1
deactivate


echo "run_tests adios at $(date)  rv ="$rv


if [ $rv == 0 ] ; then

    echo "PASSED"
else
    echo "FAILED"
fi

exit $rv




