#!/bin/bash

#start mrfbus instances
TMP=/tmp/mrf_bus
LOGDIR=${TMP}/log
#

stdbuf -oL examples/host/bin/host_0x01 > ${LOGDIR}/host_0x01.log &
h01_pid=$!
echo $h01_pid

stdbuf -oL  examples/stub/bin/hostsim_0x00 > ${LOGDIR}/stub.log&
stub_pid=$!

# make sure everyone is up

sleep 1

# run stubtst

python land/pt1000test.py

sleep 1

kill $h01_pid $h02_pid $h20_pid $h2f_pid $stub_pid

sleep 1

echo "run_tests adios at $(date)"







